env:
  browser: true
  es6: true
  webextensions: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 6
  sourceType: script
  impliedStrict: true
rules:
  no-param-reassign:
    - warn
    - props: false
